### ISSUE TITLE
Error occured when execute yolov5_demo.py?

### ISSUE THREAD

**Issue by xugaoxiang** [violet17/yolov5_demo#4]
(py37) xugaoxiang@1070Ti:~/workshop/yolov5-3.0$ python yolov5_openvino.py -m yolov5s.xml -i inference/images/bus.jpg
[ INFO ] Creating Inference Engine...
[ INFO ] Loading network files:
        yolov5s.xml
        yolov5s.bin
yolov5_openvino.py:233: DeprecationWarning: Reading network using constructor is deprecated. Please, use IECore.read_network() method instead
  net = IENetwork(model=model_xml, weights=model_bin)
[ INFO ] Preparing inputs
[ INFO ] Loading model to the plugin
[ INFO ] Starting inference...
To close the application, press 'CTRL+C' here or switch to the output window and press ESC key
To switch between sync/async modes, press TAB key in the output window
[ INFO ] Layer Transpose_215 parameters:
[ INFO ]          classes : 80
[ INFO ]          num     : 3
[ INFO ]          coords  : 4
[ INFO ]          anchors : [10.0, 13.0, 16.0, 30.0, 33.0, 23.0, 30.0, 61.0, 62.0, 45.0, 59.0, 119.0, 116.0, 90.0, 156.0, 198.0, 373.0, 326.0]
Traceback (most recent call last):
  File "yolov5_openvino.py", line 414, in <module>
    sys.exit(main() or 0)
  File "yolov5_openvino.py", line 334, in main
    args.prob_threshold)
  File "yolov5_openvino.py", line 162, in parse_yolo_region
    out_blob_n, out_blob_c, out_blob_h, out_blob_w = blob.shape
ValueError: too many values to unpack (expected 4)

Please Help!

**Comment by violet17** [comment]
@xugaoxiang  Sorry for late reponse. Have you solved this problem? Can you share more information?
